### PR TITLE
Fix get() method not respecting perPage() definitions

### PR DESCRIPTION
**Pull request by srdante**
This pull request fixs the `get()` method currently not respecting the amounts per page set for methods with pagination supported.

### CODE REVIEW

**Comment by fodderstompf** [comment]
Thanks for the PR ;)


The ternary checks will cause a breaking change due to the way the ID's are handled.
If you try to get a specific server with `$ploi->servers()->get($id);` then it will return the specific server, but if you go for the alternative `$ploi->servers($id)->get();` this will now return the result of calling `->page()`.

Could you change the check to look at `$this->getId()` instead, as that should resolve the issue.


Also, could you add the change to the Redirect resource class as that one also has pagination.

**Comment by srdante** [comment]
@fodderstompf The if to check if there $id is set is exactly to not add breaking changes.

Using `$ploi->servers($id)->get();` nowadays returns the list of *Resource*  but without respecting the amounts per page. Using the `page()` instead of `makeAPICall()` will return the same result but respecting the amounts per page.

**Comment by fodderstompf** [comment]
That example doesn't return the list, it returns the server you've passed the ID for. So it's currently a breaking change if you don't check for any ID being set.

**Comment by srdante** [comment]
Current Ploi SDK version:

```php
dump($ploi->server(1)->networkRules()->get()->getData()); // Will return the list of network rules

dump($ploi->server(1)->networkRules()->get(1)->getData()); // Will return the specific network rule based on passed ID
```

Ploi SDK after this pull request:

```php
dump($ploi->server(1)->networkRules()->get()->getData()); // Will return the list of network rules

dump($ploi->server(1)->networkRules()->get(1)->getData()); // Will return the specific network rule based on passed ID
```

You should test by your self. I think you are confusing how the SDK works on the current version.

**Comment by fodderstompf** [comment]
Not confused, your example isn't correct, so I think there is a misunderstanding.

The equivalent there would be passing an ID to network rules (`$ploi->server(1)->networkRules(1)->get()->getData()`) vs passing it to the get of network rules (`$ploi->server(1)->networkRules()->get(1)->getData()`).

**Comment by srdante** [comment]
@fodderstompf I didn't know that it was possible to pass the id in the construction of the resource, I believe that this way it should work as expected.

**Review by fodderstompf — APPROVED** [review]

**Pull request merged**
