### PR TITLE
Add webserver template option to "site create"

### PR DESCRIPTION
**Pull request by richardfrankza**

### CODE REVIEW

**Comment by fodderstompf** [comment]
Nice!
Could `$webserver_template` be changed to `$webserverTemplate` to keep consistency with the existing naming convention?

**Comment by richardfrankza** [comment]
done, all good?

**Review by Cannonb4ll — COMMENTED** [review]
Looks good to me, what do you think @fodderstompf ?

**Review by fodderstompf — APPROVED** [review]
Yeah all good 👍

**Pull request merged**
