### PR TITLE
adding project_type in site resource

### PR DESCRIPTION
**Pull request by best-lucky1030**

### CODE REVIEW

**Comment by fodderstompf** [comment]
Hey 🙂
It'd be better if the default value was null (or whatever Ploi would default to if you don't set it), so that it doesn't affect people using the SDK already.

You can hold off on that for now though because this option isn't available over the API according to the docs, so would need to be added first.

**Comment by best-lucky1030** [comment]
But users need to add project type for their projects.
for example, when I am going to deploy larave project using Ploi api, we always get null for `project_type` because there is no parma with `project_type` in Site Resource.
so i think we have to add `project_type` option as `null` so users can add their `project_type`.
if not, how can we handle this problem without using manual method in ploi dashboard?

**Comment by fodderstompf** [comment]
Sorry, what I meant was adding that to the SDK code won't actually make a difference as it's not listed as an accepted parameter for that API request: https://developers.ploi.io/sites/create-site

It would need to be added to the API first, then the SDK can be updated.

**Comment by best-lucky1030** [comment]
Oh, I thought you are owner for API and this package.
if then, do i have to submit to them(Api support team)?

**Comment by Cannonb4ll** [comment]
As described in #44 I have gone ahead and added the `project_type` parameter support in the API. As far as I am concered, this can be merged if you're ok with it @fodderstompf!

**Comment by best-lucky1030** [comment]
Yeah, after @fodderstompf check this, he can merge. thanks 👍

**Pull request merged**
