### PR TITLE
Database backups get and create

### PR DESCRIPTION
**Pull request by iamthesoundman**
Hi, I took a stab at additional database functions, getting and creating backups. I kept the code inside the Database Resource file. Wasn't sure if you planned to break it out to a separate file to match how it is in the documentation but it made the most sense to me to just keep it all under the same file. 

eg.

$ploi->server($server)->databases()->createBackup(123,0,'local',null,null,'/home/ploi/backup');

$ploi->server($server)->databases()->getBackups()
$ploi->server($server)->databases()->getBackups(123)

### CODE REVIEW

**Comment by iamthesoundman** [comment]
Oops example for getting backups should read. 

$ploi->server($server)->databases(123)->getBackups()
$ploi->server($server)->databases(123)->getBackups(123)

**Comment by Cannonb4ll** [comment]
Hey!

Awesome work, however, I see it is not following the standard we're using.

It would be nice if it uses this syntax:

`$ploi->server(1)->databases(1)->backups()->get()`

Or

`$ploi->server(1)->databases(1)->backups(1)->get()`

Just like the readme has on sites, or any other resources.

Best would be to create a new resource called `DatabaseBackup` and introduce that method inside the database resource.

**Comment by iamthesoundman** [comment]
Yeah that makes sense! I'll try to set up some time soon to break that out. I'll submit a new pull when I get that.

**Comment by Cannonb4ll** [comment]
Yeah sure, you're also more than welcome to update this PR, no problem!

**Pull request closed without merging**
